name: PyPI Nightly Build

on:
  schedule:
    # Run daily at 10:00 PM UTC
    - cron: '0 22 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  publish-test-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Use Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: npm ci
      - run: npm run build-webview
      - run: npm run build-cli
      - run: python -m pip install -e .[dev]
      
      - name: Get current version
        id: get_version
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Create development version
        run: |
          # Create a dev version with timestamp
          TIMESTAMP=$(date +%Y%m%d%H%M)
          node bump-version.js ${{ steps.get_version.outputs.version }} "$TIMESTAMP"

      - name: Build package
        run: hatch build -t wheel

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Test installation from Test PyPI
        run: |
          # Wait a bit for the package to be available
          sleep 30
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ agentlightning
          python -c "import poml; print('Package installed successfully')"
