name: PyPI Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.2.3, etc.
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-version:
    uses: ./.github/workflows/check-version.yml

  publish-to-pypi:
    needs: check-version
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            wheel_platform: manylinux_2_17_x86_64
          - os: ubuntu-24.04-arm
            wheel_platform: manylinux_2_17_aarch64
          - os: windows-latest
            wheel_platform: win_amd64
          - os: macos-13
            wheel_platform: macosx_10_9_x86_64
          - os: macos-latest
            wheel_platform: macosx_11_0_arm64

    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Use Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: npm ci
      - run: npm run build-webview
      - run: npm run build-cli
      - run: python -m pip install -e .[dev]

      - name: Build package
        run: hatch build -t wheel

      - name: Verify package contents
        run: |
          python -m zipfile -l dist/*.whl

      - name: Rename wheel for platform
        id: rename-wheel
        shell: bash
        run: |
          WHEEL_FILE=$(find dist -name "*.whl" -type f | head -1)
          if [ -z "$WHEEL_FILE" ]; then
            echo "No wheel file found!"
            exit 1
          fi
          echo "Original wheel: $WHEEL_FILE"
          
          # Parse the original wheel filename to extract components
          WHEEL_NAME=$(basename "$WHEEL_FILE" .whl)
          
          # Split wheel name into components: name-version-python_tag-abi_tag-platform_tag
          IFS='-' read -ra PARTS <<< "$WHEEL_NAME"
          
          if [ ${#PARTS[@]} -ge 5 ]; then
            DIST_NAME="${PARTS[0]}"
            VERSION="${PARTS[1]}"
            PYTHON_TAG="${PARTS[2]}"
            ABI_TAG="${PARTS[3]}"
            # Join remaining parts as platform tag
            PLATFORM_TAG=$(IFS='-'; echo "${PARTS[*]:4}")
          else
            echo "Warning: Unexpected wheel filename format: $WHEEL_NAME"
            exit 1
          fi
          
          # Create platform-specific wheel name
          PLATFORM_WHEEL="${DIST_NAME}-${VERSION}-${PYTHON_TAG}-${ABI_TAG}-${{ matrix.wheel_platform }}.whl"
          echo "Platform-specific wheel: $PLATFORM_WHEEL"
          
          # Rename the wheel file
          mv "$WHEEL_FILE" "dist/$PLATFORM_WHEEL"
          echo "wheel-file=dist/$PLATFORM_WHEEL" >> $GITHUB_OUTPUT

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.wheel_platform }}
          path: ${{ steps.rename-wheel.outputs.wheel-file }}
          compression-level: 0

      - name: Publish to Test PyPI (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI (tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Test installation from Test PyPI
        if: github.event_name == 'workflow_dispatch'
        run: |
          # Wait a bit for the package to be available
          sleep 30
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ poml==${{ needs.check-version.outputs.pypi_version }}
          python -c "import poml; print('Package installed successfully from Test PyPI')"

      - name: Test installation from PyPI
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Wait a bit for the package to be available
          sleep 30
          pip install poml==${{ needs.check-version.outputs.pypi_version }}
          python -c "import poml; print('Package installed successfully from PyPI')"
